name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci-cd-workflow:
    name: CI/CD Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run HTMLHint
      run: htmlhint .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/plain-web-app-image:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/plain-web-app-image:latest

